
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Administrator/AppData/Local/Programs/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
